version: '3'
services:

  web:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
    build: .docker
    volumes:
      - ./:/code

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./storage/database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
